package com.mostafazahra.chesswake.testutil

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Reads the golden vectors in `src/test/resources`.
 *
 * The vectors are generated by `tools/generate_test_vectors.py` with python-chess,
 * so the Kotlin engine is checked against an independent, widely used
 * implementation rather than against itself.
 */
object TestVectors {

    private val json = Json { ignoreUnknownKeys = true }

    fun load(path: String): JsonObject {
        val loader = TestVectors::class.java.classLoader
        val stream = requireNotNull(loader.getResourceAsStream(path)) {
            "missing test resource: $path"
        }
        return stream.bufferedReader().use { json.parseToJsonElement(it.readText()).jsonObject }
    }

    /** Named entries under a top-level key, e.g. `positions` or `puzzles`. */
    fun section(root: JsonObject, key: String): Map<String, JsonObject> =
        root.getValue(key).jsonObject.mapValues { (_, value) -> value.jsonObject }

    /** Ordered entries under a top-level array key, e.g. the generated puzzle list. */
    fun entries(root: JsonObject, key: String): List<JsonObject> =
        root.getValue(key).jsonArray.map { it.jsonObject }

    /** Strings under a key that must be present, e.g. a `solution` line. */
    fun strings(root: JsonObject, key: String): List<String> =
        root.getValue(key).jsonArray.map { it.jsonPrimitive.content }
}

val JsonElement.obj: JsonObject get() = jsonObject
val JsonElement.arr: JsonArray get() = jsonArray
val JsonElement.str: String get() = jsonPrimitive.content
val JsonElement.bool: Boolean get() = jsonPrimitive.boolean
val JsonElement.int: Int get() = jsonPrimitive.content.toInt()

/** `null` when the key is absent or JSON null, so optional fields stay optional. */
fun JsonObject.optionalString(key: String): String? =
    (this[key] as? JsonPrimitive)?.takeIf { it !is JsonNull }?.content

fun JsonObject.optionalInt(key: String): Int? =
    (this[key] as? JsonPrimitive)?.takeIf { it !is JsonNull }?.content?.toIntOrNull()

fun JsonObject.optionalStringList(key: String): List<String> =
    (this[key] as? JsonArray)?.map { it.jsonPrimitive.content } ?: emptyList()
