# ChessWake ProGuard / R8 rules.
#
# Room, Hilt and Compose all ship their own consumer rules, so this file only
# needs the handful of things R8 cannot infer from bytecode.

# --- Kotlin ---------------------------------------------------------------
-keepattributes *Annotation*, InnerClasses, Signature, EnclosingMethod
-dontwarn kotlin.**
-keepclassmembers class kotlin.Metadata {
    public <methods>;
}

# --- Chess engine ---------------------------------------------------------
# The engine is pure Kotlin with no reflection, but keep the public value types
# readable in crash reports so a stack trace names real classes.
-keep class com.mostafazahra.chesswake.chess.** { *; }

# --- Puzzle data ----------------------------------------------------------
# BundledPuzzles is generated by tools/generate_puzzles.py; keep it intact so
# the seeding code can always read every entry.
-keep class com.mostafazahra.chesswake.puzzle.data.BundledPuzzles { *; }

# --- Room -----------------------------------------------------------------
-keep class * extends androidx.room.RoomDatabase
-keep @androidx.room.Entity class *
-keep @androidx.room.Dao interface *

# --- Hilt / Dagger --------------------------------------------------------
-keep class dagger.hilt.** { *; }
-keep class javax.inject.** { *; }
-keepclasseswithmembers class * {
    @javax.inject.Inject <init>(...);
}

# --- Enums used across process boundaries ---------------------------------
# AlarmReceiver and SleepAsAndroidBridge pass enum names through Intents.
-keepclassmembers enum com.mostafazahra.chesswake.** {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# --- java.time ------------------------------------------------------------
# AlarmTimes uses java.time (desugaring is not needed at minSdk 26, but keep
# the classes R8 sometimes strips from the platform stubs).
-dontwarn java.time.**
